// AUTO-GENERATED by scripts/build-books.mjs. do not edit by hand.
export type Book = { name: string; file: string; size: number };
export const books: Record<string, Book[]> = {
  "aero": [
    {
      "name": "Fluid Mechanics sixth Edition Munson Okishii",
      "file": "Fluid Mechanics sixth Edition Munson Okishii.pdf",
      "size": 15126849
    },
    {
      "name": "Fundamentals_of_Aerodynamics_5th_edition",
      "file": "Fundamentals_of_Aerodynamics_5th_edition.pdf",
      "size": 27453250
    },
    {
      "name": "gas dynamics_gate pyqs_ae_qns and answer keys",
      "file": "gas dynamics_gate pyqs_ae_qns and answer keys.pdf",
      "size": 16259599
    }
  ],
  "aptitude": [],
  "flight": [
    {
      "name": "Introduction to flight 8th edition",
      "file": "Introduction to flight 8th edition.pdf",
      "size": 14485542
    }
  ],
  "math": [],
  "propulsion": [
    {
      "name": "Introduction to flight 8th edition",
      "file": "Introduction to flight 8th edition.pdf",
      "size": 14485542
    }
  ],
  "space": [
    {
      "name": "Fundamentals of Astrodynamics by Bate, Mueller, and White            ",
      "file": "Fundamentals of Astrodynamics by Bate, Mueller, and White            .pdf",
      "size": 14271916
    }
  ],
  "structures": [
    {
      "name": "Bansal R. K. - A Textbook Of Strength Of Materials_ Mechanics of Solids-Laxmi Publications (2012)",
      "file": "Bansal R. K. - A Textbook Of Strength Of Materials_ Mechanics of Solids-Laxmi Publications (2012).pdf",
      "size": 19127962
    }
  ]
};
