// scans public/books/<section>/*.pdf and writes src/lib/books.ts
import { readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = "public/books";
const OUT = "src/lib/books.ts";

const sections = readdirSync(ROOT).filter((d) => {
  try { return statSync(join(ROOT, d)).isDirectory(); } catch { return false; }
});

const data = {};
for (const s of sections) {
  const dir = join(ROOT, s);
  const files = readdirSync(dir)
    .filter((f) => f.toLowerCase().endsWith(".pdf"))
    .map((f) => {
      const size = statSync(join(dir, f)).size;
      return { name: f.replace(/\.pdf$/i, ""), file: f, size };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
  data[s] = files;
}

mkdirSync("src/lib", { recursive: true });
const body = `// AUTO-GENERATED by scripts/build-books.mjs. do not edit by hand.
export type Book = { name: string; file: string; size: number };
export const books: Record<string, Book[]> = ${JSON.stringify(data, null, 2)};
`;
writeFileSync(OUT, body);
console.log(`[books] wrote ${OUT} with ${Object.values(data).flat().length} pdfs`);
